// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract ProofOfProp {

    // mapping(address => string) public addressToName;

    struct UserParameters {
        
        string certificate_ref; // generated by our system
        string registration_date; // read data from current data function of python
        string title; // user input
        address user_address; // This should be read from address, which paid fee
        string user_name; // user input
        string additional_owner; // user input
        string user_file_hash; // hash generated and based on file chosen by user
    }

    UserParameters[] public users;

    function addUser(string memory _certificate, string memory _date, string memory _title, address _address, string memory _name, string memory _additional, string memory _hash) public {
        users.push(UserParameters(_certificate, _date, _title, _address, _name, _additional, _hash));
    }
}

